GET http://localhost:3001/products
###
curl -X POST http://localhost:3001/products
Content-Type: application/json
{
    "name" : "oneplus Nord",
    "price" : "400"
}
###
GET http://localhost:3001/products/id
###
PUT http://localhost:3001/products/id1
###
PATCH http://localhost:3001/products/id2
###
DELETE http://localhost:3001/products/id3

###
GET http://localhost:3001/

###
GET http://localhost:3001/test?name=user1&id=45

###
GET http://localhost:3001/test/3458753674578/kiran


###
GET http://localhost:3002/orders
###
POST  http://localhost:3002/orders
###
GET http://localhost:3002/orders/id
###
PUT http://localhost:3002/orders/id1 
###
PATCH http://localhost:3002/orders/id2 
###
DELETE  http://localhost:3002/orders/id3 

###
GET http://localhost:3002/


###
GET  http://localhost:3001/test/34587534/kiran

###
curl -X POST http://localhost:3001/products 
"Content-Type: application/json" -d'

{
    "name" : "oneplus Nord",
    "price" : "400"
}

###
POST  http://localhost:3001/test
Content-Type: application/application/x-www-form-urlencoded

id=34587534&user=kiran
###
curl -X POST -H 
"Content-Type: application/json" -d '
{
    "name" : "oneplus 11r",
    "price" : "1400"
}' http://localhost:3001/products

###
curl -X POST -H 
"Content-Type: application/json" -d '
{
    "name" : "oneplus 7r",
    "price" : "900"
}' http://localhost:3001/products

