GET http://localhost:3001/products
###
curl -X POST http://localhost:3001/products
Content-Type: application/json
{
    "name" : "oneplus Nord",
    "price" : "400"
}
###
GET http://localhost:3001/products/id
###
PUT http://localhost:3001/products/id1
###
PATCH http://localhost:3001/products/id2
###
DELETE http://localhost:3001/products/id3

###
GET http://localhost:3001/

###
GET http://localhost:3001/test?name=user1&id=45

###
GET http://localhost:3001/test/3458753674578/kiran

###
curl -X POST  http://localhost:3002/orders
Content-Type: application/json
{
    "items": "5",
     "price" : "6666",
      "id"   : "2343453",
     "orderdate": "10/05/2023"
}###
GET  http://localhost:3001/test/34587534/kiran

###
curl -X POST http://localhost:3001/products 
"Content-Type: application/json" -d'

{
    "name" : "oneplus Nord",
    "price" : "400"
}

###
POST  http://localhost:3001/test
Content-Type: application/application/x-www-form-urlencoded

id=34587534&user=kiran
###
curl -X POST -H 
"Content-Type: application/json" -d '
{
    "name" : "oneplus 11r",
    "price" : "1400"
}' http://localhost:3001/products

###
curl -X POST -H 
"Content-Type: application/json" -d '
{
    "name" : "oneplus 14r",
    "price" : "1600"
}' http://localhost:3001/products

